<div>
    <x-ui::checkbox
        :name="$name"
        :label="$label"
        :description="$description"
        :checked="$checked"
        :disabled="$disabled"
        wire:model.live="checked"
    />
</div>
