<div>
    <x-ui::input
        :type="$type"
        :name="$name"
        :label="$label"
        :placeholder="$placeholder"
        :hint="$hint"
        :error="$error"
        :value="$value"
        :required="$required"
        :disabled="$disabled"
        :autocomplete="$autocomplete"
        wire:model.live="value"
    />
</div>
