<div>
    <x-ui::password-input
        :name="$name"
        :label="$label"
        :required="$required"
        :strength-meter="$strengthMeter"
        :error="$error"
        :autocomplete="$autocomplete"
        wire:model.live="value"
    />
</div>
