<div>
    <x-ui::select
        :name="$name"
        :label="$label"
        :options="$options"
        :selected="$value"
        :placeholder="$placeholder"
        :required="$required"
        :disabled="$disabled"
        :error="$error"
        wire:model.live="value"
    />
</div>
