<div>
    <x-ui::textarea
        :name="$name"
        :label="$label"
        :placeholder="$placeholder"
        :value="$value"
        :rows="$rows"
        :maxlength="$maxlength"
        :show-count="$showCount"
        :required="$required"
        :error="$error"
        wire:model.live="value"
    />
</div>
